export default interface IUser {
    id?: any | null,
    username?: string,
    password?: string,
    roles?: Array<string>,
    clientId?: number,
    clientNumber?: any | null,
    referenceNumber?: any | null,
    securityPhone?: any | null,
    securityPhoneCountry?: any | null,
    lastUsernameRequestMail?: any | null,
    initials?: string,
    firstName?: string,
    betweens?: string | null,
    lastName?: string,
    cardName?: string,
    language?: string,
    languageId?: any | null,
    emailLanguage?: string,
    emailLanguageId?: number,
    occupation?: any | null,
    civilClass?: any | null,
    birthDate?: any | null,
    lengthInCm?: number,
    startWeight?: number,
    startBMI?: number,
    startWaistSize?: number | null,
    targetWeight?: number,
    targetBMI?: number,
    targetWaistSize?: number | null,
    remarks?: any | null,
    status?: string,
    creationDateTime?: any | null,
    gender?: string,
    urlClientPhoto?: any | null, 
    dietName?: string,
    consultantFullName?: string,
    fullName?: string,
    firstWeightmomentDate?: any | null,
    lastWeightmomentDate?: any | null,
    practiceId?: number,
    allowOrderingInPortal?: boolean,
    sendPortalSaleConfirmation?: boolean,
    canOrderOnline?: boolean,
    owningConsultantUserId?: number,
    firstContactDate?: any | null,
    startDietDate?: any | null,
    firstWeightmomentId?: number,
    showBirthdayInOverview?: boolean,
    location?: {
        street?: string,
        houseNumber?: any | null,
        houseNumberAddition?: any | null,
        postalCode?: any | null,
        city?: string,
        email?: string,
        websiteUrl?: any | null,
        countryId?: number,
        countryCode?: string,
        countyId?: number,
        phone1?: any | null,
        phone2?: any | null,
        subscribeNewsLetter?: boolean
    },
    discount?: number,
    sendAppointmentReminder?: boolean,
    ageInYears?: number,
    lastContactDate?: any | null,
    isApprovedForClientDetails?: boolean,
    clientWeightDetails?: {
        showFat?: boolean,
        showWaist?: boolean,
        showMoist?: boolean,
        showVisceralFat?: boolean,
        showFatFreeMass?: boolean,
        showMuscularMass?: boolean,
        showBoneMass?: boolean,
        showBmrKc?: boolean,
        showBmrKj?: boolean,
        showMetabolicAge?: boolean,
        showHealthyWeight?: boolean
    },
    organizationWeightDetails?: {
        showFat?: boolean,
        showWaist?: boolean,
        showMoist?: boolean,
        showVisceralFat?: boolean,
        showFatFreeMass?: boolean,
        showMuscularMass?: boolean,
        showBoneMass?: boolean,
        showBmrKc?: boolean,
        showBmrKj?: boolean,
        showMetabolicAge?: boolean,
        showHealthyWeight?: boolean
    },
    currentVisceralFatPercentage?: number,
    currentBodyFatMassInPercentage?: number,
    currentBodyMoistInPercentage?: number,
    countryMinimumAge?: number,
    clientUserId?: number,
    allowCWPsendnewsLetter?: boolean,
    allowConsultantSendNewsLetter?: boolean,
    lockedOutUntil?: any | null,
    intakeKey?: any | null,
    hasPif?: boolean,
    isQuestionnaireAvalaible?: boolean,
    currentPifId?: number,
    practiceCountry?: string,
    isPifComplete?: boolean,
    webcamConsultId?: any | null,
    consultantNumber?: number,
    isLockedOut?: boolean,
    availableForInSocialFeed?: boolean,
    participateToInSocial?: boolean,
    showDietProgramsTab?: boolean,
    enableWeightmomentMail?: boolean,
    excludeFromAnonymization?: boolean,
    legalCountry?: string,
    relationEndHidingTimeInDays?: number,
    clientMedicalForm?: {
        clientId?: number,
        hartinfarct?: boolean,
        hersenbloeding?: boolean,
        ernstigeHartAfwijkingen?: any | null,
        porfyrie?: boolean,
        phenylketonurie?: boolean,
        zwareDepressie?: boolean,
        eetstoornissen?: any | null,
        ernstigeLeverOfNierZiekten?: any | null,
        middelenTegenOvergewicht?: any | null,
        moaRemmers?: boolean,
        galwegenKlachten?: any | null,
        zwanger?: boolean,
        bevallenInDeAfgelopenDrieMaanden?: boolean,
        borstvoeding?: any | null,
        insulineBijDiabetesType1?: boolean,
        insulineBijDiabetesType2?: boolean,
        antistollingsmedicatie?: any | null,
        medicatieBijHartritmeStoornissen?: boolean,
        medicatieBijEpilepsie?: boolean,
        medicatieBijBipolairestoornis?: any | null,
        diurectica?: boolean,
        medicatieBijHogeBloeddruk?: boolean,
        oraleMedicatieDiabetusType2?: any | null,
        jicht?: boolean,
        jichtMedicatie?: boolean,
        depressieNietGenoemd?: boolean,
        schildklierafwijkingenNietGenoemd?: any | null,
        ziektenAanHetMaagDarmstelselNietGenoemd?: any | null,
        andereStofwisselingZiektesNietGenoemd?: any | null,
        hoogCholesterolGehalteNietGenoemd?: boolean,
        schizofreniePsychosenNietGenoemd?: boolean,
        nietGenoemdeAandoening1?: any | null,
        nietGenoemdeAandoening2?: any | null,
        glutenAllergie?: boolean,
        pindaAllergie?: boolean,
        sojaAllergie?: boolean,
        melkAllergie?: boolean,
        selderijAllergie?: boolean,
        sulfietAllergie?: boolean,
        eiAllergie?: boolean,
        sesamzaadAllergie?: boolean,
        notenAllergie?: boolean,
        mosterdAllergie?: boolean,
        lactoAllergie?: boolean,
        gistAllergie?: boolean,
        aspartaamAllergie?: boolean,
        andereAllergie?: any | null,
        overigeMedicatie?: any | null,
        medicalPassportEnclosed?: boolean
    },
    validated?: boolean,
    transferEnabled?: boolean,
    canCreateOnlineOrder?: boolean,
    canCreatePracticeOrder?: boolean,
    canAccessEConsult?: boolean
}
